# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples



# If not running interactively, don't do anything
[ -z "$PS1" ] && [ "$1" != 'force' ] && return



# Source private stuff
# Also sets $computer and $platform
[ -f "$HOME/.bashrc-private.bash" ] && source ~/.bashrc-private.bash



# Source everything in dotfiles/sh/rc.d/
if [ -d "$HOME/dotfiles/sh/rc.d" ]; then
	for f in $HOME/dotfiles/sh/rc.d/*; do
		source "$f"
	done
fi
