#!/bin/bash
# Open tmux sessions automatically on servers
if command -v tmux>/dev/null; then
	if [ -n $USE_TMUX ] ||
		[[ $computer == "pi" ]] ||
		[[ $computer == "pysweeper" ]] ||
		[[ $computer == "compcluster" ]]; then

		[[ ! $TERM =~ screen ]] &&
			[ -z $TMUX ] &&
			( tmux -2 attach || tmux -2 new )
	fi
fi
